### ISSUE TITLE
Intermittent credentials issues

### ISSUE THREAD

**Issue by jazanne** [aws-actions/configure-aws-credentials#341]
My configuration:

```yaml
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
```

Get this error intermittently, but frequently.

```
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```

It tends to happen when I have a lot of runs at the same time, for example, when dependabot opens PRs. It _generally_ will pass when I re-run the workflow manually, but it's a time suck and slows down our CI for pkg updates.

**Comment by 27Bslash6** [comment]
This is a huge issue for us at the moment, it's now occurring on nearly every pipeline run if there are more than ~3-4 simultaneous actions run in parallel. We're losing up to 30minutes per run in manual retries.

**Comment by nk9** [comment]
I'm having this problem as well, but Dependabot isn't even on in the repo in question. And it's not intermittent, it's always happening. Every attempt over the past three days has failed with the same error, whether triggered automatically or via "Re-run all jobs".

I didn't change anything about the GitHub action or the secrets, it just stopped working. The config looks identical to the one posted by jazanne. As it stands, I can no longer push my container to AWS using GH Actions. 😦

**Comment by newforma-bclemans** [comment]
+1 this issue. 

The only difference is how I instantiate the region (GitHub Secrets) but I did hard-code `aws-region: us-east-1` as a troubleshooting step and was successful in replicating the same failure: 
`"Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers"`

I deployed the below template to 150+ private repos. So far, there's 2 repos failing: 
`"Error: Input required and not supplied: aws-region" `

...but again, when I hard-code the region it provides the same error as @jazanne 

```
name: Backup GitHub Repository to Amazon S3 Bucket
on:
  push:
    branches: [main, master]
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.BACKUP_AWS_IAM_ROLE }}
          aws-region: ${{ secrets.BACKUP_AWS_REGION }}

      - name: Copy Repo to S3 Bucket
        run: |
          aws s3 sync . s3://${{ secrets.BACKUP_AWS_S3_BUCKET }}/${{ github.event.repository.name }}

```

**Comment by andrewsw** [comment]
Can confirm this problem still exists today, and might be getting worse. Our config: 

```yaml
      - name: Configure AWS credentials (HUB)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.HUB_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.HUB_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
```

We get this result, pretty consistently, on first run for a given PR: 

```
Run aws-actions/configure-aws-credentials@v1
  with:
    aws-region: us-west-2
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```

Typically succeeds on a re-run.

**Comment by andrewsw** [comment]
Still happening. Reliably failing when dependabot induces a build by opening a PR. Subsequent re-run of the job succeeds.

**Comment by jazanne** [comment]
yea same. pretty frustrating

**Comment by juiceppe** [comment]
Same here 

+1 to this issue

**Comment by Judaxx** [comment]
+1

still having it

**Comment by andrewsw** [comment]
I learned some stuff yesterday... 

https://github.com/aws-actions/configure-aws-credentials/issues/188
https://github.com/aws-actions/configure-aws-credentials/issues/202
https://github.com/dependabot/dependabot-core/issues/3253

Basically, appears to be a secrets configuration problem.

**Comment by peterwoodworth** [comment]
Unfortunately I'm not really sure what to suggest aside from seconding that it is likely a secrets configuration issue. Please refer to #271 for further comments, we're working on improving our documentation and figuring out the best strategies for authentication, so the feedback here hasn't gone unnoticed. Thanks!

**Comment by tirelibirefe** [comment]
Actually not secrets problem; it is something else:

```
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/github-actions-role
          aws-region: ${{ inputs.aws_region }}
```

...and I get:

![image](https://github.com/aws-actions/configure-aws-credentials/assets/45227339/62ae6a55-b74e-499c-908d-a50ab088560d)

**Comment by nathphoenix** [comment]
I'm currently having this issue right now, is there a way around it, so i don't have to propose using azure, same as @tirelibirefe
